%------------------------------------------------------------------------------
  %
  %  Filename      : extract
  %  Author        : Huang Leilei
  %  Created       : 2020-06-22
  %  Description   : extract with matlab
  %
%-------------------------------------------------------------------------------
  %
  %  Created       : 2020-06-22 by HLL
  %  Description   : loop for NAME_SES_A added
  %
%-------------------------------------------------------------------------------

%*** PRE ***********************************************************************
%% init
clear;
clc;
close all;

%% parameter
%NAME_SES_A = {'reference/dump'};
%NAME_SES_B = {'embed_mine_4/dump_with_seed_03'};
NAME_SES_A   = {'recode/dump_paper_with_lcu_01_embedded',    ...
                'recode/dump_paper_with_lcu_02_embedded',    ...
                'recode/dump_paper_with_lcu_03_embedded',    ...
                'recode/dump_paper_with_lcu_04_embedded',    ...
                'recode/dump_paper_with_lcu_08_embedded',    ...
                'recode/dump_paper_with_lcu_09_embedded',    ...
                'recode/dump_paper_with_lcu_10_embedded',    ...
                'recode/dump_paper_with_lcu_15_embedded',    ...
                'recode/dump_paper_with_lcu_16_embedded',    ...
                'recode/dump_paper_with_lcu_22_embedded'
};
NAME_SES_B   = {'embed_paper/dump_with_lcu_01_embedded',    ...
                'embed_paper/dump_with_lcu_15_embedded',    ...
                'embed_paper/dump_with_lcu_03_embedded',    ...
                'embed_paper/dump_with_lcu_22_embedded',    ...
                'embed_paper/dump_with_lcu_08_embedded',    ...
                'embed_paper/dump_with_lcu_09_embedded',    ...
                'embed_paper/dump_with_lcu_10_embedded',    ...
                'embed_paper/dump_with_lcu_02_embedded',    ...
                'embed_paper/dump_with_lcu_16_embedded',    ...
                'embed_paper/dump_with_lcu_04_embedded'
};
%NAME_SES_A   = {'recode/dump_mine_4_with_seed_01',    ...
%                'recode/dump_mine_4_with_seed_02',    ...
%                'recode/dump_mine_4_with_seed_03',    ...
%                'recode/dump_mine_4_with_seed_04',    ...
%                'recode/dump_mine_4_with_seed_05',    ...
%                'recode/dump_mine_4_with_seed_06',    ...
%                'recode/dump_mine_4_with_seed_07',    ...
%                'recode/dump_mine_4_with_seed_08',    ...
%                'recode/dump_mine_4_with_seed_09',    ...
%                'recode/dump_mine_4_with_seed_10'
%};
%NAME_SES_B   = {'embed_mine_4/dump_with_seed_01',    ...
%                'embed_mine_4/dump_with_seed_08',    ...
%                'embed_mine_4/dump_with_seed_03',    ...
%                'embed_mine_4/dump_with_seed_04',    ...
%                'embed_mine_4/dump_with_seed_10',    ...
%                'embed_mine_4/dump_with_seed_06',    ...
%                'embed_mine_4/dump_with_seed_07',    ...
%                'embed_mine_4/dump_with_seed_02',    ...
%                'embed_mine_4/dump_with_seed_09',    ...
%                'embed_mine_4/dump_with_seed_05'
%};
NAME_SEQ     = 'BlowingBubbles';
DATA_Q_P     = '22';
SIZE_FRA_X   = 416;
SIZE_FRA_Y   = 240;
NUMB_FRA     = 20;
DATA_THR_DIF = 20;
FLAG_PLT     = 0;
INDX_PLT     = "A";
FLAG_STP     = 0;
NUMB_SES_A   = numel(NAME_SES_A);
NUMB_SES_B   = numel(NAME_SES_B);


%*** MAIN BODY *****************************************************************
%% main loop
% loop A
for idxA = 1:NUMB_SES_B
    % get name_Ses_A
    name_Ses_A = NAME_SES_A{idxA};

    % loop B
    datPsnr = zeros(NUMB_SES_B, 1);
    for idxB = 1:NUMB_SES_B
        % get name_Ses_B
        name_Ses_B = NAME_SES_B{idxB};

        % core
        datTmp = extract_core(['../', name_Ses_A, '/', NAME_SEQ, '_', DATA_Q_P, '/', 'x265.yuv']    ...
                     ,        ['../', name_Ses_B, '/', NAME_SEQ, '_', DATA_Q_P, '/', 'x265.yuv']    ...
                     ,        SIZE_FRA_X                                                            ...
                     ,        SIZE_FRA_Y                                                            ...
                     ,        NUMB_FRA                                                              ...
                     ,        DATA_THR_DIF                                                          ...
                     ,        FLAG_PLT                                                              ...
                     ,        INDX_PLT                                                              ...
                     ,        FLAG_STP                                                              ...
        );

        % save data
        datPsnr(idxB) = median(datTmp(:,1));
    end

    % plot
    figure(2);
    hold on;
    plot(datPsnr);
    plot(datPsnr, 'ko');
end


%*** POST **********************************************************************
% tune
set(gcf, 'position', [500, 500, 560, 420]);
title('watermarking extraction');
axis([0, NUMB_SES_B+1, min(datPsnr) - 5, max(datPsnr) + 5]);
grid on;
xlabel('sequence index');
ylabel('psnr');

% save
fig = getframe(gcf);
img = frame2im(fig);
imwrite(img, ['dump/psnr.png']);
